// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBErI_VMhBO30x9VPNQUlEvgUZmeIeD8VI',
    appId: '1:184241487527:web:8ad754e22ec23e6cc82582',
    messagingSenderId: '184241487527',
    projectId: 'firstprojecct-4e7bb',
    authDomain: 'firstprojecct-4e7bb.firebaseapp.com',
    storageBucket: 'firstprojecct-4e7bb.appspot.com',
    measurementId: 'G-WX8P05P8TY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADf_YEy0xJjoGg95Hv1JEL2fGxveQrRA8',
    appId: '1:184241487527:android:a03a140ebd195f45c82582',
    messagingSenderId: '184241487527',
    projectId: 'firstprojecct-4e7bb',
    storageBucket: 'firstprojecct-4e7bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZBCy-Nr_65E5cdKisPvEkQx_Ra-EG63s',
    appId: '1:184241487527:ios:e507cd2a20ca3306c82582',
    messagingSenderId: '184241487527',
    projectId: 'firstprojecct-4e7bb',
    storageBucket: 'firstprojecct-4e7bb.appspot.com',
    iosBundleId: 'com.example.page',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZBCy-Nr_65E5cdKisPvEkQx_Ra-EG63s',
    appId: '1:184241487527:ios:4117cd8c46c713e2c82582',
    messagingSenderId: '184241487527',
    projectId: 'firstprojecct-4e7bb',
    storageBucket: 'firstprojecct-4e7bb.appspot.com',
    iosBundleId: 'com.example.page.RunnerTests',
  );
}
